ruby_app/config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  resources :users

  namespace :api do
    resources :users
  end

  resources :events do
    resources :event_guests
    collection do
      get :export_all
      post :import
    end
    get :export
  end

  get 'auth/:provider/callback', to: "sessions#googleAuth"
  get 'auth/failure', to: redirect('/')
  delete 'disconnect_google/:id', to: "sessions#disconnect"

  # get 'auth/google_oauth2', to: redirect('/auth/google_oauth2')

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

ruby_app/app/models/event.rb
class Event < ApplicationRecord
  has_many :event_guests, dependent: :destroy

  attr_accessor :start_date_part, :start_time_part, :end_date_part, :end_time_part, :guest_ids

  before_save :combine_date_time
  before_update :combine_date_time

  def combine_date_time
    if start_date_part.present? && start_time_part.present?
      self.start_time = Time.parse("#{ start_date_part } #{ start_time_part }");
    end

    if end_date_part.present? && end_time_part.present?
      self.end_time = Time.parse("#{ end_date_part } #{ end_time_part }");
    end
  end
end

ruby_app/app/controllers/events_controller.rb
require 'csv'

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_users, only: %i[new create]

  def index
    @events = Event.all.order('start_time').decorate
  end

  def show
    @users = User.all.decorate
  end

  def import
    file = params[:file]
    csv_import_usecase = CsvUsecase.new(file)
    response = csv_import_usecase.import
    if response[:status] == :ok
      redirect_to events_path, notice: "Events imported success!"
    end
  end

  def export_all
    @events = Event.all
    export_all_service = Events::EventService.new(nil)
    csv_data = export_all_service.export_all(@events)

    respond_to do |format|
      format.csv do
        send_data csv_data, filename: 'events.csv', type: 'text/csv'
      end
    end
  end

  def export
    @event = Event.find(params[:event_id])
    event_export_service = Events::EventService.new(nil)
    csv_data = event_export_service.export(@event)

    respond_to do |format|
      format.csv { send_data csv_data, filename: "event_#{@event.title}.csv", type: "text/csv" }
    end
  end

  def new
    @event = Event.new
  end

  def create
    respond_to do |format|
      begin
        event_create_usecase = Events::EventUsecase.new(event_params)
        response = event_create_usecase.create
        if response[:status] == :created
          format.html { redirect_to events_path, notice: t("messages.common.create_success", data: "Event") }
        else
          flash[:errors] = response[:errors]
          flash[:alert] = t("messages.common.create_fail", data: "Event")
          @event = response[:event]
          format.html { render :new, status: :unprocessable_entity, errors: response[:errors]}
        end
      rescue StandardError => errors
        logger.error "Something went wrong while creating the event. #{ errors.message }"
        format.html { render file: "#{ Rails.root }/public/500.html", layout: true, status: :internal_server_error }
      end
    end
  end

  def edit
    @event.start_date_part = @event.start_time.to_date
    @event.start_time_part = @event.start_time.strftime('%H:%M')
    @event.end_date_part = @event.end_time.to_date
    @event.end_time_part = @event.end_time.strftime('%H:%M')
    @users = User.all.decorate
    @guest_ids = @event.event_guests.pluck(:user_id)
  end

  def update
    update_event = Events::EventUsecase.new(event_params)
    respond_to do |format|
      response = update_event.update(@event)
      if response[:status] == :updated
        format.html { redirect_to @event, notice: t('messages.common.update_success', data: "Event") }
        format.json { render :show, status: :ok, location: @event }
      else
        @event.start_date_part = @event.start_time.to_date
        @event.start_time_part = @event.start_time.strftime('%H:%M')
        @event.end_date_part = @event.end_time.to_date
        @event.end_time_part = @event.end_time.strftime('%H:%M')
        @users = User.all.decorate
        @guest_ids = @event.event_guests.pluck(:user_id)
        flash.now[:alert] = t('messages.common.update_fail', data: "Event")
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    delete_event = Events::EventUsecase.new(nil)

    respond_to do |format|
      if delete_event.destroy(@event)
        format.html { redirect_to events_url, notice: t('messages.common.destroy_success', data: "Event") }
        format.json { head :no_content }
      end
    end
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :start_date_part, :start_time_part, :end_date_part, :end_time_part, guest_ids: [])
    end

    def set_event
      @event = Event.find(params[:id]).decorate
    end

    def set_users
      @users = User.all.order('first_name').decorate
      @guest_ids = []
    end
end

ruby_app/app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="mb-5">
  <div>
    <h4>
      <%= event.title %>
      <% if event.start_time <= Time.current() && event.end_time >= Time.current() %>
        <span class="badge text-bg-success float-end" style="font-size: small">Ongoing</span>
      <% elsif event.start_time > Time.current() %>
        <span class="badge text-bg-primary float-end" style="font-size: small">Upcoming</span>
      <% else %>
        <span class="badge text-bg-secondary float-end" style="font-size: small">ended</span>
      <% end %>
    </h4>
  </div>
  <div class="mb-3">
    <div class="d-inline-block me-3">
      <span class="">From : </span>
      <%= event.formated_start_time %>
    </div>
    <div class="d-inline-block">
      <span class="">To : </span>
      <%= event.formated_end_time %>
    </div>
    <% unless viewEventDetails %>
      <div>
        Total guests - <%= event.event_guests.count %>
      </div>
    <% end %>
  </div>
  <div class="text-muted mb-4">
    <span class="fs-italic">Description - </span>
    <%= event.description %>
  </div>

  <% if viewEventDetails %>
    <div class="">
      <div class="border-bottom border-2 border-primary mb-2">
        <h4>Guests</h4>
      </div>
      <div class="row">
        <% event.event_guests.each do |event_guest| %>
          <div class="col-4 p-2">
            <div class="bg-light d-flex align-items-center p-2 rounded">
              <div class="me-3">
                <div class="rounded-circle border border-3 <%= 'border-success' if event_guest.google_event_id.present? %>">
                  <%= image_tag event_guest.user.profile, style: "width: 50px; border-radius:50%", class: "border border-2 border-light" %>
                </div>
              </div>
              <div>
                <%= event_guest.user.decorate.full_name %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

ruby_app/app/views/events/_form.html.erb
<% flash.discard %>
<%= form_with(model: event, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label t('labels.event.title'), class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
    <% if flash[:errors].present? && flash[:errors]["title"].present? %>
      <% flash[:errors]["title"].each do |error| %>
        <span style="color: red; display: block;"><%= error %></span>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <div class="row">
      <div class="col">
        <%= form.label t('labels.event.start_time'), class: "form-label" %>
        <div class="row">
          <div class="col">
            <%= form.date_field :start_date_part, id: "startDatePart", class: "form-control", required: true %>
          </div>
          <div class="col">
            <%= form.time_field :start_time_part, id: "startTimePart", class: "form-control", required: true %>
          </div>
        </div>
        <% if flash[:errors].present? && flash[:errors]["start_time"].present? %>
          <% flash[:errors]["start_time"].each do |error| %>
            <span style="color: red; display: block;"><%= error %></span>
          <% end %>
        <% end %>
      </div>
      <div class="col">
        <%= form.label t('labels.event.end_time'), class: "form-label" %>
        <div class="row">
          <div class="col">
            <%= form.date_field :end_date_part, id: "endDatePart", class: "form-control", required: true %>
          </div>
          <div class="col">
            <%= form.time_field :end_time_part, id: "endTimePart", class: "form-control", required: true %>
          </div>
        </div>
        <% if flash[:errors].present? && flash[:errors]["end_time"].present? %>
          <% flash[:errors]["end_time"].each do |error| %>
            <span style="color: red; display: block;"><%= error %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label t('labels.event.description'), class: "form-label" %>
    <%= form.text_area :description, class: "form-control", required: true %>
    <% if flash[:errors].present? && flash[:errors]["description"].present? %>
      <% flash[:errors]["description"].each do |error| %>
        <span style="color: red; display: block;"><%= error %></span>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label t('labels.event.guests'), class: "form-label"  %>
    <%= form.collection_select :guest_ids, users, :id, :full_name, { selected: @guest_ids }, { id: "guests", multiple: true, class: "form-control", required: true } %>
    <% if flash[:errors].present? && flash[:errors]["guest_ids"].present? %>
      <% flash[:errors]["guest_ids"].each do |error| %>
        <span style="color: red; display: block;"><%= error %></span>
      <% end %>
    <% end %>
  </div>
  <div class="text-center">
    <% if local_assigns[:form_type] == :edit %>
      <%= form.submit t('buttons.common.update', data: "Event"), class: "btn btn-primary" %>
    <% else %>
      <%= form.submit t('buttons.common.create', data: "Event"), class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

<script>
  var startDateField = $('#startDatePart');
  var startTimeField = $('#startTimePart');
  var endDateField = $('#endDatePart');
  var endTimeField = $('#endTimePart');

  function padToTwoDigits(number) {
    return number.toString().padStart(2, '0');
  }

  function setStartTime() {
    const now = new Date();

    var min = now.getMinutes();

    if (min > 0 && min < 5) {
      now.setMinutes(15);
    } else if (min > 5 && min < 20) {
      now.setMinutes(30);
    } else if (min > 20 && min < 35) {
      now.setMinutes(45);
    } else if (min > 35 && min < 50) {
      now.setMinutes(60);
    } else if (min > 50) {
      now.setMinutes(75);
    }

    var startHours = padToTwoDigits(now.getHours());
    var startMinutes = padToTwoDigits(now.getMinutes());
    var formattedStartTime = `${startHours}:${startMinutes}`;

    return formattedStartTime;
  }

  function addThirtyMinutes(startTime){
    const time = startTime.split(":");

    var endDateTime = new Date();
    endDateTime.setHours(parseInt(time[0]));
    endDateTime.setMinutes(parseInt(time[1]) + 30);

    var endHours = padToTwoDigits(endDateTime.getHours());
    var endMinutes = padToTwoDigits(endDateTime.getMinutes());
    var formattedEndTime = `${endHours}:${endMinutes}`;

    return formattedEndTime;
  }

  function updateEndDate() {
    endDateField.val(startDateField.val())
  }

  function updateEndTime() {
    endTimeField.val(addThirtyMinutes(startTimeField.val()));
  }

  startDateField.on('change', function() {
    if (!endDateField.val() || endDateField.val() < startDateField.val()) {
      updateEndDate();
      updateEndTime();
    }
  })

  startTimeField.on('change', function() {
    if ((startDateField.val() == endDateField.val()) && (addThirtyMinutes(startTimeField.val()) > endTimeField.val())) {
      updateEndTime();
    }
  })

  if(!startDateField.val()) {
    var now = new Date();
    var year = now.getFullYear();
    var month = padToTwoDigits(now.getMonth() + 1);
    var day = padToTwoDigits(now.getDate());
    var formattedDate = `${year}-${month}-${day}`;

    startDateField.val(formattedDate);
    endDateField.val(formattedDate);
  }

  if(!startTimeField.val()) {
    var formattedStartTime = setStartTime();

    var formattedEndTime = addThirtyMinutes(formattedStartTime)

    startTimeField.val(formattedStartTime)
    endTimeField.val(formattedEndTime)
  }

  <% if flash[:errors].present? %>
    $(document).ready(function() {
      $('#guests').select2({
        placeholder: "Select Guests",
        allowClear: true
      });
    })
  <% else %>
    document.addEventListener('turbo:load', function () {
      $('#guests').select2({
        placeholder: "Select Guests",
        allowClear: true
      });
    });
  <% end %>
</script>

ruby_app/app/views/events/edit.html.erb
<div class="container mt-5 px-5 py-3 border border-dark-50 rounded bg-light" style="width: 800px;">
  <h4 class="text-center">Edit Event</h4>
  <% if flash[:alert].present? %>
    <div class="alert alert-warning mx-auto text-center">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="mt-3">
    <%= render "form", event: @event, users: @users, form_type: :edit %>
  </div>
</div>

ruby_app/app/views/events/index.html.erb
<div id="events" class="container p-3 mt-3" style="width: 800px">
  <% if notice.present? %>
    <div class="alert alert-info mx-auto text-center">
      <%= notice %>
    </div>
  <% end %>

  <div class="position-relative">
    <div class="position-absolute end-0 z-index:3">
      <%= link_to "Export Events", "/events/export_all.csv", class: "btn btn-sm" %>
    </div>
    <h3 class="text-center mb-4">
      Events
    </h3>
  </div>
  <% @events.each do |event| %>
    <div class="row mb-3">
      <div class="card">
        <div class="card-body">
          <%= render partial: "event", locals: { event: event, viewEventDetails: false } %>
          <div class="float-end">
            <%= link_to "View this event", event, class: "text-dark" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

ruby_app/app/views/events/new.html.erb
<div class="container mt-5 px-5 py-3 border border-dark-50 rounded bg-light" style="width: 800px;">
  <h4 class="text-center">New Event</h4>
  <% if flash[:alert].present? %>
    <div class="alert alert-warning mx-auto text-center">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="mt-3">
  <%= render "form", event: @event, users: @users %>
  </div>
  <div class="mt-3 border rounded">
    <%= form_tag import_events_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "import csv" %>
    <% end %>
  </div>
</div>

ruby_app/app/views/events/show.html.erb
<div class="container p-3 mt-3" style="width: 800px;">
  <h4 class="text-center mb-4">Event Details</h4>

  <% if notice.present? %>
    <div class="alert alert-info mx-auto text-center">
      <%= notice %>
    </div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-warning mx-auto text-center">
      <%= alert %>
    </div>
  <% end %>
  <div class="border border-dark-50 rounded p-5">
    <%= render partial: "event", locals: { event: @event, viewEventDetails: true } %>

    <div class="d-flex justify-content-center">

    <% if @event.start_time > Time.current() %>
      <%= link_to t('buttons.common.edit', data: 'Event'), edit_event_path(@event), class: "btn btn-success me-2" %>
    <% else %>
      <button class="btn btn-success me-2" disabled>Unable to edit</button>
    <% end %>
      <%= button_to t('buttons.common.delete', data: 'Event'), @event, method: :delete, class: "btn btn-danger me-2" %>
      <%= link_to "Export", "/events/#{@event.id}/export.csv", class: "btn btn-outline-secondary" %>
    </div>
  </div>

</div>