ruby_app/config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  resources :users

  namespace :api do
    resources :users
  end

  resources :events do
    resources :event_guests
    collection do
      get :export_all
      post :import
    end
    get :export
  end

  get 'auth/:provider/callback', to: "sessions#googleAuth"
  get 'auth/failure', to: redirect('/')
  delete 'disconnect_google/:id', to: "sessions#disconnect"

  # get 'auth/google_oauth2', to: redirect('/auth/google_oauth2')

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

ruby_app/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg nabar-dark">
  <div class="container">
    <%= link_to "DataX", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "User Lists", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Events", events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create User", new_user_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Event", new_event_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>